<template>
  <div class="live-page">
    <div class="live-hero"><div><h2>开播录入</h2><p>记录开播数据并自动计算薪酬</p></div><div class="live-actions"><el-button @click="exportRows">导出 CSV</el-button><el-upload :show-file-list="false" accept=".csv" :auto-upload="false" :on-change="importCsv"><el-button>批量导入</el-button></el-upload><el-button type="primary" v-hasPermi="['wms:live:stream:edit']" @click="openDialog()">新增开播记录</el-button></div></div>
    <div class="metric-grid"><el-card v-for="item in metrics" :key="item.label" class="metric-card" shadow="never"><div class="metric-label">{{ item.label }}</div><div class="metric-value">{{ item.value }}</div><div class="metric-hint">当前筛选页汇总</div></el-card></div>
    <el-card class="live-filter" shadow="never"><el-form :inline="true"><el-form-item label="日期"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" /></el-form-item><el-form-item><el-input v-model="query.keyword" clearable placeholder="搜索录入人/备注" /></el-form-item><el-form-item><el-select v-model="query.employeeId" filterable clearable placeholder="全部主播"><el-option v-for="v in options.employees" :key="v.value" :label="v.label" :value="v.value" /></el-select></el-form-item><el-form-item><el-select v-model="query.accountId" clearable placeholder="全部账号"><el-option v-for="v in options.accounts" :key="v.id" :label="accountLabel(v)" :value="v.id" /></el-select></el-form-item><el-form-item><el-select v-model="query.rateTypeId" clearable placeholder="全部费率类型"><el-option v-for="v in options.rateTypes" :key="v.id" :label="v.typeName" :value="v.id" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
    <el-card class="live-card" shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="streamDate" label="日期" width="110" /><el-table-column prop="accountLabel" label="账号" min-width="180" /><el-table-column prop="employeeName" label="主播" /><el-table-column label="时间" width="150"><template #default="s">{{ shortTime(s.row.startTime) }} - {{ shortTime(s.row.endTime) }}</template></el-table-column><el-table-column label="工时"><template #default="s">{{ Number(s.row.durationHours || 0).toFixed(2) }}h</template></el-table-column><el-table-column prop="rateTypeName" label="费率类型"><template #default="s"><el-tag class="type-tag">{{ s.row.rateTypeName }}</el-tag></template></el-table-column><el-table-column label="时薪"><template #default="s">{{ money(s.row.hourlyRate) }}<sup v-if="s.row.manualRate">*</sup></template></el-table-column><el-table-column label="特殊"><template #default="s"><span :class="Number(s.row.specialAmount) >= 0 ? 'positive' : 'negative'">{{ money(s.row.specialAmount) }}</span></template></el-table-column><el-table-column label="总金额"><template #default="s"><strong>{{ money(s.row.totalAmount) }}</strong></template></el-table-column><el-table-column prop="enteredBy" label="录入人" /><el-table-column label="操作" width="130" fixed="right"><template #default="s"><el-button link type="primary" @click="openDialog(s.row)">{{ tr('编辑') }}</el-button><el-button link type="danger" @click="remove(s.row)">{{ tr('删除') }}</el-button></template></el-table-column></el-table><pagination v-show="total>0" :total="total" v-model:page="query.pageNum" v-model:limit="query.pageSize" @pagination="load" /></el-card>

    <el-dialog v-model="dialog.open" :title="dialog.form.id ? '编辑开播记录' : '新增开播记录'" width="760px" append-to-body><el-form ref="formRef" :model="dialog.form" :rules="rules" label-width="92px"><div class="dialog-grid"><el-form-item label="日期" prop="streamDate"><el-date-picker v-model="dialog.form.streamDate" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="主播" prop="employeeId"><el-select v-model="dialog.form.employeeId" filterable><el-option v-for="v in options.employees" :key="v.value" :label="v.label" :value="v.value" /></el-select></el-form-item><el-form-item label="账号" prop="accountId"><el-select v-model="dialog.form.accountId"><el-option v-for="v in options.accounts" :key="v.id" :label="accountLabel(v)" :value="v.id" /></el-select></el-form-item><el-form-item label="费率类型" prop="rateTypeId"><el-select v-model="dialog.form.rateTypeId"><el-option v-for="v in options.rateTypes" :key="v.id" :label="`${v.typeName} (×${v.multiplier})`" :value="v.id" /></el-select></el-form-item><el-form-item label="开始时间" prop="startTime"><el-time-picker v-model="dialog.form.startTime" value-format="HH:mm:ss" format="HH:mm" /></el-form-item><el-form-item label="结束时间" prop="endTime"><el-time-picker v-model="dialog.form.endTime" value-format="HH:mm:ss" format="HH:mm" /></el-form-item><el-form-item label="手工时薪"><el-switch v-model="dialog.form.manualRate" /></el-form-item><el-form-item label="时薪"><el-input-number v-model="dialog.form.hourlyRate" :disabled="!dialog.form.manualRate" :min="0" :precision="2" /></el-form-item><el-form-item class="wide" label="特殊明细"><div style="width:100%"><div v-for="(item,index) in dialog.specials" :key="index" class="live-actions" style="margin-bottom:8px"><el-select v-model="item.typeId" style="width:190px" @change="applySpecialSign(item)"><el-option v-for="v in options.specialTypes" :key="v.id" :label="tr(v.typeName)" :value="v.id" /></el-select><el-input-number v-model="item.amount" :precision="2" style="width:170px" /><el-input v-model="item.remark" placeholder="备注" /><el-button type="danger" link @click="dialog.specials.splice(index,1)">{{ tr('删除') }}</el-button></div><el-button text type="primary" @click="dialog.specials.push({ typeId:null, amount:0, remark:'' })">+ 新增一条</el-button><span style="float:right">合计：<strong>{{ money(specialTotal) }}</strong></span></div></el-form-item><el-form-item class="wide" label="备注"><el-input v-model="dialog.form.remark" type="textarea" /></el-form-item></div></el-form><template #footer><el-button @click="dialog.open=false">取消</el-button><el-button type="primary" @click="submit">提交</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed, getCurrentInstance, onMounted, reactive, ref } from 'vue'
import { addStream, batchStreams, deleteStream, getLiveOptions, listStreams, updateStream } from '@/api/wms/livePayroll'
import useSettingsStore from '@/store/modules/settings'
import { translateByMap } from '@/locales/runtime-map'
import { accountLabel, downloadCsv, isoDate, money, monthRange, parseCsv } from '../shared'
const settingsStore=useSettingsStore(),tr=(text)=>translateByMap(text,settingsStore.language||'zh-cn')
const { proxy } = getCurrentInstance()
const loading = ref(false), rows = ref([]), total = ref(0), formRef = ref()
const dateRange = ref(monthRange()), options = reactive({ employees: [], accounts: [], rateTypes: [], specialTypes: [] })
const query = reactive({ pageNum: 1, pageSize: 20, keyword: '', employeeId: null, accountId: null, rateTypeId: null })
const dialog = reactive({ open: false, form: {}, specials: [] })
const rules = { streamDate: [{ required: true, message: '请选择日期' }], employeeId: [{ required: true, message: '请选择主播' }], accountId: [{ required: true, message: '请选择账号' }], rateTypeId: [{ required: true, message: '请选择费率类型' }], startTime: [{ required: true, message: '请选择开始时间' }], endTime: [{ required: true, message: '请选择结束时间' }] }
const specialTotal = computed(() => dialog.specials.reduce((sum, v) => sum + Number(v.amount || 0), 0))
const metrics = computed(() => { const hours = rows.value.reduce((s,v)=>s+Number(v.durationHours||0),0), pay = rows.value.reduce((s,v)=>s+Number(v.totalAmount||0),0), types = new Set(rows.value.map(v=>v.rateTypeId)).size; return [{ label:'总场次', value: total.value }, { label:'当前页工时', value:`${hours.toFixed(2)}h` }, { label:'费率类型数', value:types }, { label:'当前页薪酬', value:money(pay) }] })
async function load() { loading.value = true; try { const res = await listStreams({ ...query, startDate: dateRange.value?.[0], endDate: dateRange.value?.[1] }); rows.value = res.rows || []; total.value = res.total || 0 } finally { loading.value = false } }
function reset() { dateRange.value = monthRange(); Object.assign(query, { pageNum:1, keyword:'', employeeId:null, accountId:null, rateTypeId:null }); load() }
function shortTime(value) { return String(value || '').slice(0,5) }
function openDialog(row = {}) { let specials=[]; try { specials = JSON.parse(row.specialDetails || '[]') } catch (_) {} dialog.form = { id:row.id, streamDate:row.streamDate || isoDate(), employeeId:row.employeeId || null, accountId:row.accountId || null, rateTypeId:row.rateTypeId || null, startTime:row.startTime || '09:00:00', endTime:row.endTime || '17:00:00', manualRate:Boolean(row.manualRate), hourlyRate:Number(row.hourlyRate || 0), remark:row.remark || '', customFields:row.customFields || '{}' }; dialog.specials=specials; dialog.open=true }
function applySpecialSign(item) { const type=options.specialTypes.find(v=>v.id===item.typeId); if (type?.category==='DEDUCTION' && Number(item.amount)>0) item.amount=-Number(item.amount); if (type?.category==='SUBSIDY' && Number(item.amount)<0) item.amount=Math.abs(Number(item.amount)) }
async function submit() { await formRef.value.validate(); const payload={ ...dialog.form, specialAmount:specialTotal.value, specialDetails:JSON.stringify(dialog.specials) }; await (payload.id ? updateStream(payload) : addStream(payload)); proxy.$modal.msgSuccess('保存成功'); dialog.open=false; load() }
async function remove(row) { await proxy.$modal.confirm(`确认删除 ${row.employeeName} ${row.streamDate} 的开播记录？`); await deleteStream(row.id); proxy.$modal.msgSuccess('删除成功'); load() }
function exportRows() { downloadCsv(`开播记录-${dateRange.value?.[0]}-${dateRange.value?.[1]}.csv`, [{key:'streamDate',label:'日期'},{key:'employeeName',label:'主播'},{key:'accountLabel',label:'账号'},{key:'startTime',label:'开始时间'},{key:'endTime',label:'结束时间'},{key:'durationHours',label:'工时'},{key:'rateTypeName',label:'费率类型'},{key:'hourlyRate',label:'时薪'},{key:'specialAmount',label:'特殊金额'},{key:'totalAmount',label:'总金额'},{key:'remark',label:'备注'}], rows.value) }
async function importCsv(uploadFile) { try { const raw=await parseCsv(uploadFile.raw); const payload=raw.map(v=>({ streamDate:v['日期'], employeeId:options.employees.find(e=>e.label===v['主播'])?.value, accountId:options.accounts.find(a=>accountLabel(a)===v['账号'] || a.accountCode===v['账号'])?.id, rateTypeId:options.rateTypes.find(t=>t.typeName===v['费率类型'])?.id, startTime:(v['开始时间']||'09:00')+':00', endTime:(v['结束时间']||'17:00')+':00', manualRate:Boolean(v['时薪']), hourlyRate:Number(v['时薪']||0), specialAmount:Number(v['特殊金额']||0), specialDetails:'[]', remark:v['备注']||'' })); await batchStreams(payload); proxy.$modal.msgSuccess(`成功导入 ${payload.length} 条`); load() } catch (e) { proxy.$modal.msgError(e.message || '导入失败') } }
onMounted(async()=>{ Object.assign(options, await getLiveOptions()); load() })
</script>
<style scoped lang="scss">@import '../live.scss';</style>

