<template>
  <div class="live-page">
    <div class="live-hero"><div><h2>系统设置</h2><p>配置公司信息、币种、费率类型与自定义字段</p></div><el-button type="primary" @click="save">保存设置</el-button></div>
    <el-card class="live-card settings-section" shadow="never"><template #header>公司信息</template><el-form :model="setting" label-width="120px"><div class="dialog-grid"><el-form-item label="公司名称"><el-input v-model="setting.companyName" /></el-form-item><el-form-item label="默认币种"><el-select v-model="setting.currency"><el-option v-for="v in currencies" :key="v" :label="v" :value="v" /></el-select></el-form-item><el-form-item label="时区"><el-select v-model="setting.timezone"><el-option v-for="v in timezones" :key="v" :label="v" :value="v" /></el-select></el-form-item><el-form-item label="系统默认时薪"><el-input-number v-model="setting.defaultHourlyRate" :precision="2" :min="0" /></el-form-item><el-form-item class="wide"><el-alert title="计算公式：总金额 = 实际工时 × 时薪 + 特殊金额。时薪按“主播 + 账号 + 费率类型 + 日期”匹配最近生效记录。" type="info" :closable="false" /></el-form-item></div></el-form></el-card>
    <el-card class="live-card settings-section" shadow="never"><template #header><div style="display:flex;justify-content:space-between;align-items:center"><span>费率类型管理 · {{ rateTypes.filter(v=>v.status===0).length }} 启用</span><el-button type="primary" link @click="openRateType()">新增类型</el-button></div></template><p class="muted">停用的类型新增记录时不可选，但历史记录会保留。</p><el-table :data="rateTypes" stripe><el-table-column prop="typeName" label="名称" /><el-table-column label="描述"><template #default="s">{{ tr(s.row.description) }}</template></el-table-column><el-table-column label="来源"><template #default="s"><el-tag :type="s.row.source==='SYSTEM'?'info':''">{{ tr(s.row.source==='SYSTEM'?'系统':'自定义') }}</el-tag></template></el-table-column><el-table-column label="状态"><template #default="s"><el-switch v-model="s.row.status" :active-value="0" :inactive-value="1" @change="quickSaveRateType(s.row)" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="s"><el-button link type="primary" @click="openRateType(s.row)">{{ tr('编辑') }}</el-button><el-button v-if="s.row.source!=='SYSTEM'" link type="danger" @click="removeRateType(s.row)">{{ tr('删除') }}</el-button></template></el-table-column></el-table></el-card>
    <el-card class="live-card settings-section" shadow="never"><template #header><div style="display:flex;justify-content:space-between;align-items:center"><span>特殊金额类型管理 · {{ specialTypes.filter(v=>v.status===0).length }} 启用</span><el-button type="primary" link @click="openSpecialType()">新增类型</el-button></div></template><p class="muted">用于开播录入的交通补贴、餐补、奖金、扣款等特殊明细。</p><el-table :data="specialTypes" stripe><el-table-column label="名称"><template #default="s">{{ tr(s.row.typeName) }}</template></el-table-column><el-table-column label="分类"><template #default="s"><el-tag :type="s.row.category==='DEDUCTION'?'danger':s.row.category==='SUBSIDY'?'success':'info'">{{ categoryLabel(s.row.category) }}</el-tag></template></el-table-column><el-table-column label="状态"><template #default="s"><el-switch v-model="s.row.status" :active-value="0" :inactive-value="1" @change="quickSaveSpecialType(s.row)" /></template></el-table-column><el-table-column label="操作" width="130"><template #default="s"><el-button link type="primary" @click="openSpecialType(s.row)">{{ tr('编辑') }}</el-button><el-button link type="danger" @click="removeSpecialType(s.row)">{{ tr('删除') }}</el-button></template></el-table-column></el-table></el-card>
    <el-card class="live-card settings-section" shadow="never"><template #header>自定义字段 · {{ customFields.length }} 个字段</template><p class="muted">为开播记录添加额外字段，例如直播间号、转化率等。</p><div v-for="(field,index) in customFields" :key="index" class="live-actions" style="margin-bottom:10px"><el-input v-model="field.name" placeholder="字段名称" style="width:220px" /><el-input v-model="field.key" placeholder="Key" style="width:220px" /><el-button link type="danger" @click="customFields.splice(index,1)">{{ tr('删除') }}</el-button></div><el-button text type="primary" @click="customFields.push({name:'',key:''})">+ 添加字段</el-button></el-card>

    <el-dialog v-model="rateDialog.open" :title="rateDialog.form.id?'编辑费率类型':'新增费率类型'" width="520px"><el-form :model="rateDialog.form" label-width="90px"><el-form-item label="名称"><el-input v-model="rateDialog.form.typeName" /></el-form-item><el-form-item label="描述"><el-input v-model="rateDialog.form.description" /></el-form-item><el-form-item label="状态"><el-radio-group v-model="rateDialog.form.status"><el-radio :label="0">启用</el-radio><el-radio :label="1">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="rateDialog.open=false">取消</el-button><el-button type="primary" @click="submitRateType">保存</el-button></template></el-dialog>
    <el-dialog v-model="specialDialog.open" :title="specialDialog.form.id?'编辑特殊金额类型':'新增特殊金额类型'" width="500px"><el-form :model="specialDialog.form" label-width="90px"><el-form-item label="名称"><el-input v-model="specialDialog.form.typeName" /></el-form-item><el-form-item label="分类"><el-select v-model="specialDialog.form.category"><el-option :label="tr('补贴类')" value="SUBSIDY" /><el-option :label="tr('扣款类')" value="DEDUCTION" /><el-option :label="tr('其他')" value="OTHER" /></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="specialDialog.form.status"><el-radio :label="0">启用</el-radio><el-radio :label="1">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="specialDialog.open=false">取消</el-button><el-button type="primary" @click="submitSpecialType">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { getCurrentInstance, onMounted, reactive, ref } from 'vue'
import { addRateType, addSpecialType, deleteRateType, deleteSpecialType, getLiveSetting, listRateTypes, listSpecialTypes, updateLiveSetting, updateRateType, updateSpecialType } from '@/api/wms/livePayroll'
import useSettingsStore from '@/store/modules/settings'
import { translateByMap } from '@/locales/runtime-map'
const {proxy}=getCurrentInstance()
const settingsStore=useSettingsStore(),tr=(text)=>translateByMap(text,settingsStore.language||'zh-cn')
const setting=reactive({id:null,companyName:'LUXE AF LIVE',currency:'USD',timezone:'UTC-8',payUnit:'HOUR',defaultHourlyRate:0}),customFields=ref([]),rateTypes=ref([]),specialTypes=ref([])
const currencies=['USD','CNY','EUR','GBP','JPY','KRW'],timezones=['UTC+8','UTC+9','UTC+7','UTC-5','UTC-8','UTC+0']
const rateDialog=reactive({open:false,form:{}}),specialDialog=reactive({open:false,form:{}})
async function load(){const [s,r,sp]=await Promise.all([getLiveSetting(),listRateTypes(),listSpecialTypes()]);Object.assign(setting,s.data||{});try{customFields.value=JSON.parse(setting.customFields||'[]')}catch(_){customFields.value=[]}rateTypes.value=r.data||[];specialTypes.value=sp.data||[]}
async function save(){const fields=customFields.value.filter(v=>v.name||v.key).map(v=>({name:String(v.name||'').trim(),key:String(v.key||'').trim()}));if(fields.some(v=>!v.name||!v.key))return proxy.$modal.msgWarning('自定义字段的名称和 Key 都不能为空');if(new Set(fields.map(v=>v.key)).size!==fields.length)return proxy.$modal.msgWarning('自定义字段 Key 不能重复');await updateLiveSetting({...setting,payUnit:'HOUR',customFields:JSON.stringify(fields)});proxy.$modal.msgSuccess('设置已保存')}
function openRateType(row={}){rateDialog.form={id:row.id,typeName:row.typeName||'',description:row.description||'',source:row.source||'CUSTOM',status:row.status??0,sortOrder:row.sortOrder||rateTypes.value.length*10+10};rateDialog.open=true}
async function submitRateType(){if(!rateDialog.form.typeName)return proxy.$modal.msgWarning('请输入名称');await(rateDialog.form.id?updateRateType(rateDialog.form):addRateType(rateDialog.form));rateDialog.open=false;load()}
async function quickSaveRateType(row){await updateRateType(row);proxy.$modal.msgSuccess('状态已更新')}
async function removeRateType(row){await proxy.$modal.confirm(`确认删除 ${row.typeName}？`);await deleteRateType(row.id);load()}
function openSpecialType(row={}){specialDialog.form={id:row.id,typeName:row.typeName||'',category:row.category||'OTHER',status:row.status??0,sortOrder:row.sortOrder||specialTypes.value.length*10+10};specialDialog.open=true}
async function submitSpecialType(){if(!specialDialog.form.typeName)return proxy.$modal.msgWarning('请输入名称');await(specialDialog.form.id?updateSpecialType(specialDialog.form):addSpecialType(specialDialog.form));specialDialog.open=false;load()}
async function quickSaveSpecialType(row){await updateSpecialType(row);proxy.$modal.msgSuccess('状态已更新')}
async function removeSpecialType(row){await proxy.$modal.confirm(`确认删除 ${row.typeName}？`);await deleteSpecialType(row.id);load()}
function categoryLabel(v){return tr(v==='SUBSIDY'?'补贴类':v==='DEDUCTION'?'扣款类':'其他')}
onMounted(load)
</script>
<style scoped lang="scss">@import '../live.scss';</style>
